# Generated by Django 5.2.13 on 2026-05-01 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блок "О нас"',
                'verbose_name_plural': 'Блок "О нас"',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('map_coordinates', models.CharField(blank=True, help_text='Например: 55.751244,37.618423', max_length=100, verbose_name='Координаты карты')),
                ('map_zoom', models.PositiveSmallIntegerField(default=12, verbose_name='Масштаб карты')),
                ('work_time', models.CharField(default='Пн-Пт: 9:00-18:00', max_length=200, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название цели')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, upload_to='goals/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Наши цели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GovernorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Показывать блок')),
                ('name', models.CharField(default='Андрей Воробьёв', max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(default='Губернатор Московской области', max_length=200, verbose_name='Должность')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('image', models.ImageField(upload_to='governor/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Блок губернатора',
                'verbose_name_plural': 'Блок губернатора',
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Вместе поможем', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Фоновое изображение')),
                ('button1_text', models.CharField(default='Присоединиться', max_length=50, verbose_name='Текст первой кнопки')),
                ('button1_link', models.CharField(default='#', max_length=200, verbose_name='Ссылка первой кнопки')),
                ('button2_text', models.CharField(default='Связаться', max_length=50, verbose_name='Текст второй кнопки')),
                ('button2_link', models.CharField(default='#contacts', max_length=200, verbose_name='Ссылка второй кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Главный блок',
                'verbose_name_plural': 'Главный блок',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Член руководства',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('type', models.CharField(choices=[('main', 'Основной'), ('hotline', 'Горячая линия'), ('fax', 'Факс'), ('other', 'Дополнительный')], default='other', max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='main.contactinfo', verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['order'],
            },
        ),
    ]
