# Generated by Django 5.2.13 on 2026-05-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutblock',
            name='image',
        ),
    ]
