# Generated by Django 5.2.13 on 2026-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_aboutblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Вместе на передовой - вместе в мирной жизни', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.TextField(blank=True, default='Объединение участников СВО и ветеранов боевых действий...', verbose_name='Подзаголовок Hero')),
                ('hero_button1_text', models.CharField(default='Присоединиться к Ассоциации', max_length=50, verbose_name='Текст кнопки 1')),
                ('hero_button2_text', models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки 2')),
                ('team_title', models.CharField(default='Руководство Ассоциации', max_length=200, verbose_name='Заголовок блока "Руководство"')),
                ('team_subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок')),
                ('about_title', models.CharField(default='О нас', max_length=200, verbose_name='Заголовок "О нас"')),
                ('about_text', models.TextField(blank=True, default='', verbose_name='Текст "О нас"')),
                ('goals_title', models.CharField(default='Наши цели', max_length=200, verbose_name='Заголовок блока "Наши цели"')),
                ('goals_subtitle', models.CharField(default='Ассоциация ветеранов СВО создана для защиты прав и всесторонней поддержки...', max_length=500, verbose_name='Подзаголовок')),
                ('projects_title', models.CharField(default='Наши проекты', max_length=200, verbose_name='Заголовок блока "Наши проекты"')),
                ('projects_subtitle', models.CharField(default='Социальные, спортивные и культурные события, объединяющие ветеранов Московской области', max_length=500, verbose_name='Подзаголовок')),
                ('events_title', models.CharField(default='Анонс мероприятий', max_length=200, verbose_name='Заголовок блока "Анонс мероприятий"')),
                ('events_subtitle', models.CharField(default='Присоединяйтесь к нашим событиям - участвуйте, общайтесь, находите поддержку', max_length=500, verbose_name='Подзаголовок')),
                ('videos_title', models.CharField(default='Видеогалерея', max_length=200, verbose_name='Заголовок блока "Видеогалерея"')),
                ('videos_subtitle', models.CharField(default='Истории ветеранов, репортажи с мероприятий и важные обращения', max_length=500, verbose_name='Подзаголовок')),
                ('videos_all_button_text', models.CharField(default='Посмотреть все видео', max_length=50, verbose_name='Текст кнопки "Все видео"')),
                ('news_title', models.CharField(default='Новости', max_length=200, verbose_name='Заголовок блока "Новости"')),
                ('news_subtitle', models.CharField(default='Актуальные события и последние новости из жизни Ассоциации ветеранов СВО', max_length=500, verbose_name='Подзаголовок')),
                ('faq_title', models.CharField(default='Часто задаваемые вопросы', max_length=200, verbose_name='Заголовок блока "FAQ"')),
                ('faq_subtitle', models.CharField(default='', max_length=500, verbose_name='Подзаголовок')),
                ('contacts_title', models.CharField(default='Наши контакты', max_length=200, verbose_name='Заголовок блока "Контакты"')),
            ],
            options={
                'verbose_name': 'Тексты блоков',
                'verbose_name_plural': 'Тексты блоков',
            },
        ),
    ]
