# Generated by Django 5.2.13 on 2026-05-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='faq_subtitle',
        ),
    ]
