# Generated by Django 5.2.13 on 2026-05-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sitecontent_faq_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'verbose_name': 'Заголовки информационных блоков', 'verbose_name_plural': 'Заголовки информационных блоков'},
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_title',
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='contacts_title',
            field=models.CharField(default='Наши контакты', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='events_title',
            field=models.CharField(default='Анонс мероприятий', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='faq_title',
            field=models.CharField(default='Часто задаваемые вопросы', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='goals_title',
            field=models.CharField(default='Наши цели', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Объединение участников СВО и ветеранов боевых действий...', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_title',
            field=models.CharField(default='Вместе на передовой - вместе в мирной жизни', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='news_title',
            field=models.CharField(default='Новости', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='projects_title',
            field=models.CharField(default='Наши проекты', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='team_title',
            field=models.CharField(default='Руководство Ассоциации', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='videos_title',
            field=models.CharField(default='Видеогалерея', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новости',
                'ordering': ['order'],
            },
        ),
    ]
