# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('fact', 'Фактическая ошибка'), ('typo', 'Опечатка'), ('other', 'Другое')], max_length=20, verbose_name='Тип проблемы')),
                ('message', models.TextField(verbose_name='Что некорректно')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт для уточнений')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='Страница отправки')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Браузер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Сообщение о некорректности',
                'verbose_name_plural': 'Сообщения о некорректности',
                'ordering': ['-created_at'],
            },
        ),
    ]
