# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_issuereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueReport',
        ),
    ]
