# Generated by Codex on 2026-05-13

from django.db import migrations, models


def update_existing_button_text(apps, schema_editor):
    HeroBlock = apps.get_model('main', 'HeroBlock')
    HeroBlock.objects.filter(button1_text='Присоединиться').update(
        button1_text='Присоединиться к ассоциации'
    )
    HeroBlock.objects.filter(button2_text='Связаться').update(
        button2_text='Связаться с нами'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='button1_text',
            field=models.CharField(default='Присоединиться к ассоциации', max_length=50, verbose_name='Текст первой кнопки'),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='button2_text',
            field=models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст второй кнопки'),
        ),
        migrations.RunPython(update_existing_button_text, migrations.RunPython.noop),
    ]
